<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Atm.Client.Domain\Atm.Client.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Refit" Version="15.2.0" />
    <PackageReference Include="Refit.HttpClientFactory" Version="15.2.0" />
    <PackageReference Include="Refit.Reflection" Version="15.2.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
